# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-11 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0015_auto_20160911_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acl',
            name='AllowedNodes',
        ),
        migrations.RemoveField(
            model_name='acl',
            name='user',
        ),
        migrations.DeleteModel(
            name='Acl',
        ),
        migrations.DeleteModel(
            name='SecurityNode',
        ),
    ]
