# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-11 09:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('access', '0016_auto_20160911_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[(b'Door', b'DOOR'), (b'Tool', b'TOOL')], default=b'Door', max_length=3)),
                ('logging', models.BooleanField(default=True)),
                ('telegram', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='acl',
            name='AllowedNodes',
            field=models.ManyToManyField(to='access.SecurityNode'),
        ),
        migrations.AddField(
            model_name='acl',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
